"""modified fields in subscribers table

Revision ID: 841758099d7e
Revises: 588103cf586a
Create Date: 2021-09-26 03:39:32.534518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841758099d7e'
down_revision = '588103cf586a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
